/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.79
 * Generated at: 2023-08-30 07:00:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	margin: 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width: 1890px;\r\n");
      out.write("	border: 5px solid skyblue;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("header {\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width: 285px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section div {\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	width: 500px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("ul>li {\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("	display: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".b {\r\n");
      out.write("	width: 60%;\r\n");
      out.write("	padding: 10px;\r\n");
      out.write("}\r\n");
      out.write("a{\r\n");
      out.write("	color: black;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover{\r\n");
      out.write("	color: skyblue;\r\n");
      out.write("}\r\n");
      out.write("table {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	width: 900px;\r\n");
      out.write("	border: 3px solid #8e582a;\r\n");
      out.write("	background-color: #f5e2b1;\r\n");
      out.write("	border-radius: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	border: 1px solid #8e582a;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	border-radius: 5px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead {\r\n");
      out.write("	background-color: #f5e2b1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("thead>tr>td {\r\n");
      out.write("	height: 32px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody {\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("tbody>tr>td {\r\n");
      out.write("	height: 28px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		<img alt=\"\" src=\"./img/로고.png\">\r\n");
      out.write("		<h2>🔵매표소 : 티켓 정보🔵</h2>\r\n");
      out.write("	</header>\r\n");
      out.write("	<nav>\r\n");
      out.write("		<hr>\r\n");
      out.write("		<ul>\r\n");
      out.write("			<li><a href=\"register.jsp\">회원가입</a></li>\r\n");
      out.write("			<li><a href=\"결제하기.jsp\">결제하기</a></li>\r\n");
      out.write("			<li><a href=\"조회.jsp\">사용자조회</a></li>\r\n");
      out.write("			<li><a href=\"manager_list.jsp\">관리자조회</a></li>\r\n");
      out.write("			<li><a href=\"index.jsp\">홈으로</a></li>\r\n");
      out.write("		</ul>\r\n");
      out.write("		<hr>\r\n");
      out.write("	</nav>\r\n");
      out.write("	<section>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img alt=\"\" src=\"./img/l마스코드.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"b\">\r\n");
      out.write("			<table>\r\n");
      out.write("	\r\n");
      out.write("				<thead>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>티켓번호</td>\r\n");
      out.write("						<td>티켓종류</td>\r\n");
      out.write("						<td>티켓이용시간 종류</td>\r\n");
      out.write("						<td>티켓이용시간</td>\r\n");
      out.write("						<td>나이</td>\r\n");
      out.write("						<td>가격</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</thead>\r\n");
      out.write("				");

				Connection con = null;
				Statement st = null;
				ResultSet rs = null;
				try {
					String driver = "oracle.jdbc.driver.OracleDriver";
					String url = "jdbc:oracle:thin:@localhost:1521:xe";
					String user = "scott";
					String password = "tiger";

					//1. 오라클드라이버 로딩
					Class.forName(driver); //2. 데이터베이스 연결
					con = DriverManager.getConnection(url, user, password); //3. statement 얻어오기
					st = con.createStatement();
					//4. 필요한 sql 작성
					String sql = "select * from ticket_tbl";
					//5. 최종적으로 실행
					System.out.println(sql);
					rs = st.executeQuery(sql);
					//6. 가져온 쿼리 결과를 화면에 출력하기
					while (rs.next()) {
				
      out.write("\r\n");
      out.write("				<!-- db연동후 데이터 조회부분 -->\r\n");
      out.write("				<tbody>\r\n");
      out.write("					<tr>\r\n");
      out.write("						<td>");
      out.print(rs.getString(1));
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("						<td>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("					</tr>\r\n");
      out.write("				</tbody>\r\n");
      out.write("				");

				}
				} catch (Exception e) {
				e.printStackTrace();
				} finally { //자원의 반납
				if (rs != null)
				rs.close();
				if (st != null)
				st.close();
				if (con != null)
				con.close();
				}
				
      out.write("\r\n");
      out.write("			</table>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<img alt=\"\" src=\"./img/r마스코드.png\">\r\n");
      out.write("		</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	<footer> </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
